/**
 * Rebuild the PNG install icons from public/logo.jpg.
 *
 *   npm run icons
 *
 * The mark is artwork, not geometry — it came off the original Hoid's Journal
 * and its starfield does not survive being redrawn — so the icons are scaled
 * from the plate rather than rasterised from public/mark.svg. mark.svg is the
 * reduced line version, hand-drawn, and is only the tab favicon; it is not
 * generated by this script and the two are not expected to match pixel for
 * pixel.
 *
 * Quantising to 192 colours takes the 512 from ~340KB to ~83KB. The plate is
 * mostly noise-textured near-black, so the banding a gradient would show has
 * nowhere to appear.
 */
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'public/logo.jpg');

let magick;
try {
  magick = execFileSync('sh', ['-c', 'command -v magick || command -v convert'], {
    encoding: 'utf8',
  }).trim();
} catch {
  throw new Error('ImageMagick (magick/convert) is not on PATH; needed to scale the icon plate');
}
if (!existsSync(src)) throw new Error(`missing ${src}`);

// Sharpen a little harder going down to 192: the rose's arms are a pixel wide
// at that size and Lanczos alone leaves them grey.
const passes = [
  { size: 512, unsharp: '0x0.75+0.55+0.008' },
  { size: 192, unsharp: '0x0.6+0.5+0.01' },
];

for (const { size, unsharp } of passes) {
  const out = join(root, 'public', `icon-${size}.png`);
  execFileSync(magick, [
    src,
    '-filter', 'Lanczos',
    '-resize', `${size}x${size}`,
    '-unsharp', unsharp,
    '-dither', 'FloydSteinberg',
    '-colors', '192',
    '-define', 'png:compression-level=9',
    `PNG8:${out}`,
  ]);
  console.log(`wrote ${out}`);
}
