import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
import puppeteer from 'puppeteer-core';
const exe = ['/usr/bin/chromium','/usr/bin/google-chrome-stable','/usr/bin/google-chrome'].find(p=>require('fs').existsSync(p));
const browser = await puppeteer.launch({ executablePath: exe, headless: true,
  args: ['--no-sandbox','--headless=new','--enable-gpu','--use-gl=angle','--use-angle=gl-egl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader','--disable-dev-shm-usage','--window-size=1512,900'] });
const page = await browser.newPage();
await page.setViewport({ width: 1512, height: 900 });
await page.goto('http://127.0.0.1:5174/', { waitUntil: 'domcontentloaded' });
await page.waitForFunction('window.__ceph !== undefined', { timeout: 60000, polling: 200 });
await page.evaluate(() => {
  window.__ceph.ui?.enter();
  window.__ceph.store.set('cameraCue', { kind: 'skip-cinematic' });
  window.__ceph.store.set('visual', { ...window.__ceph.store.state.visual, quality: 'high' });
  window.__ceph.store.set('chrome', { directory:false, minimap:false, timeline:false });
});
await new Promise(r => setTimeout(r, 2500));
await new Promise(r => setTimeout(r, 1500));
const fps = () => page.evaluate(() => new Promise(res => {
  let n = 0; const t0 = performance.now();
  const tick = () => { n++; if (performance.now() - t0 < 1800) requestAnimationFrame(tick); else res(Math.round(n / ((performance.now()-t0)/1000))); };
  requestAnimationFrame(tick);
}));
const set = (code) => page.evaluate(code);
const rows = [];
rows.push(['cosmere', await fps()]);
await set(`window.__ceph.store.set('visual', {...window.__ceph.store.state.visual, showNebula:false})`);
rows.push(['cosmere - nebulae', await fps()]);
await set(`window.__ceph.store.set('visual', {...window.__ceph.store.state.visual, showNebula:true})`);
await set(`window.__ceph.store.set('realm','cognitive')`);
await new Promise(r => setTimeout(r, 2500));
rows.push(['cognitive cosmere', await fps()]);
await set(`window.__ceph.app.shadesmar.souls.visible = false`);
rows.push(['  - souls', await fps()]);
await set(`window.__ceph.app.shadesmar.souls.visible = true; for (const i of window.__ceph.app.shadesmar.islands) i.mesh.visible = false;`);
rows.push(['  - islands', await fps()]);
await set(`for (const r of window.__ceph.app.shadesmar.routes) r.line.visible = false;`);
rows.push(['  - routes too', await fps()]);
await set(`for (const i of window.__ceph.app.shadesmar.islands) i.mesh.visible = true; for (const r of window.__ceph.app.shadesmar.routes) r.line.visible = true;`);
await set(`window.__ceph.store.set('visual', {...window.__ceph.store.state.visual, showNebula:false})`);
rows.push(['  - nebulae too', await fps()]);
await set(`window.__ceph.app.shadesmar.souls.visible = true; window.__ceph.store.set('visual', {...window.__ceph.store.state.visual, showNebula:true})`);
await set(`window.__ceph.store.set('realm','spiritual')`);
await new Promise(r => setTimeout(r, 2500));
rows.push(['spiritual', await fps()]);
await set(`window.__ceph.store.set('realm','physical')`);
await new Promise(r => setTimeout(r, 1500));
await page.evaluate(() => window.__ceph.store.set('cameraCue', { kind: 'focus', id: 'roshar', scale: 'globe' }));
await new Promise(r => setTimeout(r, 4000));
rows.push(['baseline globe', await fps()]);
await set(`window.__ceph.app.starfield.sky.visible = false`); rows.push(['- sky dome', await fps()]);
await set(`window.__ceph.app.starfield.sky.visible = true; window.__ceph.store.set('visual', {...window.__ceph.store.state.visual, showAtmospheres:false})`); rows.push(['- atmosphere', await fps()]);
await set(`window.__ceph.store.set('visual', {...window.__ceph.store.state.visual, showAtmospheres:true}); for (const n of window.__ceph.app.orrery.bodyNodes.values()) n.mat.uniforms.uDetail.value = 0`); rows.push(['- surface detail', await fps()]);
await set(`for (const n of window.__ceph.app.orrery.bodyNodes.values()) n.mat.uniforms.uClouds.value = 0`); rows.push(['- clouds too', await fps()]);
await set(`window.__ceph.app.post.composer.passes[2].enabled = false`); rows.push(['- SMAA too', await fps()]);
await set(`window.__ceph.app.post.composer.passes[1].enabled = false`); rows.push(['- all post too', await fps()]);
console.log(rows.map(r => r[0].padEnd(20) + r[1]).join('\n'));
await browser.close();
